/**
 * Where uploaded files are kept. Keys are always generated by the API (never taken from the
 * client), so implementations can rely on them being short, relative, slash-separated paths.
 */
export interface FileStorage {
  put(key: string, data: Uint8Array): Promise<void>;
  /** Removes a file. Deleting a file that doesn't exist is not an error. */
  delete(key: string): Promise<void>;
}
